name: debt-dao-pools

plugins:
  - name: vyper
  - name: foundry
  # - name: etherscan
  # - name: alchemy
  # - name: hardhat 
  # - name: ledger

ethereum:
  default_network: local
  # local:
  #   uri: http://localhost:8545 # anvil mainnet fork
    # default_provider: foundry
  # mainnet_fork:
  #   default_provider: foundry
  #   # default_provider: hardhat
  #   transaction_acceptance_timeout: 99999999
  # mainnet:
  #   transaction_acceptance_timeout: 99999999

# deployments:
#   ethereum:
#     mainnet:
#       - contract_type: PoolDelegate
#         address: 0
#       - contract_type: ChikkinFactory
#         address: 0

foundry:
  # default_network: test
  local:
    uri: http://localhost:8545 # anvil mainnet fork
  test:
      uri: http://localhost:8545 # anvil mainnet fork
