classDiagram
class DebtDAOPool {
  >>Interfaces>>
  ERC4626
  ERC3156
  ERC2612
  >>Pool Spec>>
  name 'Debt DAO Pool - Credit Coop DAI'
  symbol 'ddpDAI-CCOOP'
}
Depositor --> PoolDelegate : trusts
PoolDelegate : Professional Credit Investor
Depositor: Yield Farmers
Depositor: Normies

Depositor --> DebtDAOPool : deposits
PoolDelegate --> DebtDAOPool : owns
<<Actor>> PoolDelegate
<<Actor>> Depositor

SecuredLine --> DebtDAOPool : repay
DebtDAOPool --> SecuredLine : lend
DebtDAOPool --> SecuredLine : borrows
DebtDAOPool --> SecuredLine : repays
DebtDAOPool --> Vault : invests
Spigot --> DebtDAOPool : owns
Spigot --> SecuredLine : repays
SecuredLine --> Spigot : owns
Depositor --> SecuredLine : lend
<<Contract>> Spigot
<<Contract>> DebtDAOPool
<<Contract>> SecuredLine
<<Contract>> Vault

Factory --> DebtDAOPool : deploys
Factory --> ChikkinManager : deploys
Factory --> bToken : deploys
Factory --> bNFT : deploys
Factory --> BasePool : deploys
BasePool : 3pool
BasePool : sETH/ETH
Factory --> MetaPool : deploys
MetaPool : DebtDAOPool
MetaPool : BasePool
Factory --> BondPool : deploys
BondPool : BondToken
BondPool : MetaPool
<<Contract>> Factory

class Bondoooor {
  >>Motives>>
  Buy bToken when low premium
  Mint bond base token when high premium
  ChikkinOut when premium falls
  ChikkinIn when premium increases
}

class bNFT {
  >>Function>>
  holds bond position data
  vests bToken to bNFT holder
}

Bondoor --> bNFT : holds
Bondoor --> ChikkinManager : mints
ChikkinManager --> bNFT : mints
ChikkinManager --> bToken : mints
ChikkinManager --> bToken : redeems

ChikkinManager --> Reserves: manages
ChikkinManager --> Vault: invests
ChikkinManager --> yvcrvbddpToken: invests
ChikkinManager --> yvcrvddpToken: invests
<<Actor>> Bondoooor
<<Contract>> ChikkinManager


bToken : "bddp Token"
bToken --> yvcrvbddpToken
DebtDAOPool --> yvcrvddpToken
yvcrvddpToken : "Vault for ddp CRV LP tokens"
yvcrvbddpToken : "Vault for bddp CRV LP tokens"
yvcrvddpToken --> MetaPool : farm
yvcrvbddpToken --> BondPool : farm

Pool --> yvcrvbddpToken : recursive ponzi farm

SecuredLine --> Borrower

class Reserves {
  >>Pots>>
  pending
  reserve
  permanent
  >>Assets>>
  base_asset
  bToken
  yvcrvbddpToken
  yvcrvddpToken
}

